name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal --filter 'BlurHashSharp.Tests' --collect:"XPlat Code Coverage" --results-directory coverage
    - name: Upload coverage to Codecov
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: bash <(curl -s https://codecov.io/bash)
